Repository averbis/averbis-python-api, pull requests merged in 2021-02, with the labels that each got.

#16 Issue #15: Use pathing that works independently of how to the tests are executed
  tests/test_client.py
  tests/test_pipeline.py
Labels: refactoring

#14 Adds a documentation section to the readme
  README.rst
Labels: documentation

#11 Issue #8: Change language default value to None
  averbis/core/_rest_client.py
Labels: bug

#10 #9: Experimental support for obtaining an analysed text as a UIMA CAS
  averbis/core/_rest_client.py
Labels: enhancement

#18 #17 - Documentation for get_type_system and analyse_text_to_cas not generated
  averbis/core/_rest_client.py
Labels: bug
