Repository averbis/averbis-python-api, pull requests merged in 2021-06, with the labels that each got.

#45 Issue #42 - Create Terminology dropy KeyError bugfix
  averbis/core/_rest_client.py
Labels: bug

#48 Issue #46: Adapt to Process API changes
  averbis/core/_rest_client.py
  tests/test_client.py
  tests/test_process.py
Labels: enhancement

#50 #49 - Simple method to check if a project exists
  averbis/core/_rest_client.py
  tests/test_client.py
Labels: enhancement

#36 Issue #34: Support for exporting a document from a collection
  averbis/core/_rest_client.py
  setup.py
  tests/fixtures.py
  tests/test_highlighting.py
  tests/test_pipeline.py
  tests/test_process.py
  tests/test_project.py
Labels: refactoring

#61 Issue 58: Moving built info out of constructor
  averbis/core/_rest_client.py
  tests/test_pipeline.py
Labels: enhancement
