Repository averbis/averbis-python-api, pull requests merged in 2021-09, with the labels that each got.

#84 Issue 80 - Expose top level parameters
  averbis/core/_rest_client.py
Labels: enhancement

#85 Issue #80: Deleting projects
  averbis/core/_rest_client.py
  tests/fixtures.py
  tests/test_client.py
  tests/test_document_collection.py
  tests/test_pear.py
  tests/test_pipeline.py
  tests/test_process.py
  tests/test_project.py
Labels: enhancement

#86 Issue #52: Allow listing pipelines
  averbis/core/_rest_client.py
  tests/test_project.py
Labels: enhancement

#90 #89 - Upgrade to DKPro Cassis 0.6.0
  setup.py
Labels: refactoring

#92 #91 - Exporting type systems of text analysis results does not work
  averbis/core/_rest_client.py
  tests/test_process.py
Labels: bug

#93 #89 - Upgrade to DKPro Cassis 0.6.1
  setup.py
Labels: refactoring
