Repository averbis/averbis-python-api, pull requests merged in 2021-07, with the labels that each got.

#56 Feature/55 allow importing pre annotated data
  averbis/core/_rest_client.py
  tests/test_document_collection.py
Labels: enhancement

#65 Bug/59 export text analysis not experimental anymore
  averbis/core/_rest_client.py
  tests/test_process.py
Labels: bug

#64 Issue #63: Use results type system instead of obtaining one from the pipeline
  averbis/core/_rest_client.py
  tests/test_process.py
Labels: refactoring

#66 Refactoring/54 move process from project to document level
  averbis/core/_rest_client.py
  tests/test_process.py
  tests/test_project.py
Labels: refactoring

#67 Issue #60: Improving error messages
  averbis/core/_rest_client.py
  tests/test_client.py
  tests/test_project.py
Labels: enhancement

#71 document collection list processes
  .gitignore
  averbis/core/_rest_client.py
  tests/test_client.py
  tests/test_document_collection.py
Labels: enhancement

#72 Feature/69 process on process
  averbis/core/_rest_client.py
  tests/test_document_collection.py
  tests/test_process.py
  tests/test_project.py
  tests/utils.py
Labels: enhancement

#74 Issue #73: adding collection_process_complete
  averbis/core/_rest_client.py
  tests/test_pipeline.py
Labels: enhancement
