Repository averbis/averbis-python-api, pull requests merged in 2022-02, with the labels that each got.

#104 Feature/103 add update textanalysis result
  averbis/core/_rest_client.py
  tests/fixtures.py
  tests/test_document_collection.py
  tests/test_process.py
Labels: enhancement

#106 #100 - Remove annotation_types from analyse_text_to_cas as platform does not support this parameter
  averbis/core/_rest_client.py
Labels: bug

#109 #108 - Update to cassis 0.7.0
  setup.py
Labels: refactoring
