Repository averbis/averbis-python-api, pull requests merged in 2025-08, with the labels that each got.

#182 Branch and Path Triggers Updated:
  .github/workflows/run_tests.yml
Labels: ⚙️ Refactoring

#176 Issue #174: Support document import in json format
  averbis/core/_rest_client.py
  tests/resources/json/metadata-example.json
  tests/test_document_collection.py
Labels: ⭐️ Enhancement

#172 Issue #166: Enable FHIR response for analyze_text endpoint
  averbis/core/_rest_client.py
  tests/fixtures.py
  tests/test_pipeline.py
Labels: ⭐️ Enhancement

#199 Issue #198: Switch to uv and taskipy for build
  .github/workflows/python-ci-build.yml
  .gitignore
  CONTRIBUTING.md
  Makefile
  docs/Makefile
  pyproject.toml
  setup.py
  uv.lock
Labels: ⚙️ Refactoring

#197 Issue #193: Reprocess only some documents of a process
  averbis/core/_rest_client.py
  tests/fixtures.py
  tests/test_process.py
Labels: ⭐️ Enhancement

#200 Issue #194 return status code with requestexception
  averbis/__init__.py
  averbis/core/__init__.py
  averbis/core/_rest_client.py
  tests/test_client.py
Labels: ⭐️ Enhancement

#205 Issue 203: Export enum TextanalysisMode
  averbis/__init__.py
  averbis/core/__init__.py
Labels: 🪳 Bug

#206 Issue 204: Export selected documents' textanalysis results
  averbis/core/_rest_client.py
  tests/test_process.py
Labels: ⭐️ Enhancement

#202 Issue #201: Bump minimal Python version to 3.9
  .github/workflows/python-ci-build.yml
  pyproject.toml
  uv.lock
Labels: ⚙️ Refactoring
